apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-service
  name: kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-service
  template:
    metadata:
      labels:
        service: kafka-service
    spec:
      containers:
      - image: pearlicia/kafka-service:v1
        name: kafka-service
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_TOPIC
          value: location
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_HOST
          value: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local:9092
      restartPolicy: Always
