apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-service
  name: location-service
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5000
    nodePort: 30013
  selector:
    service: location-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-service
  name: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-service
  template:
    metadata:
      labels:
        service: location-service
    spec:
      containers:
      - image: pearlicia/location-service:v1
        name: location-service
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_TOPIC
          value: location
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_HOST
          value: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local:9092
      restartPolicy: Always
